"""
Data models and schemas for AI/ML Inference & Threat Classification.
Provides standardized ML prediction contracts and label normalizations.
"""

from typing import List, Optional
from pydantic import BaseModel, Field
from enum import Enum


class MLLabel(str, Enum):
    BENIGN = "benign"
    PHISHING = "phishing"
    BEC = "bec"
    IMPERSONATION = "impersonation"
    MALICIOUS = "malicious"
    UNKNOWN = "unknown"


class MLPrediction(BaseModel):
    """
    Standardized result contract for ML model inference.
    Provider-agnostic structure consumable by the risk engine and API response.
    """
    status: str = Field(
        default="unavailable",
        description="Inference status: 'available' | 'unavailable' | 'error'"
    )
    label: str = Field(
        default=MLLabel.UNKNOWN.value,
        description="Normalized prediction label: benign | phishing | bec | impersonation | malicious | unknown"
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Model confidence score between 0.0 and 1.0 (uncalibrated unless explicitly specified)"
    )
    model_name: str = Field(
        default="none",
        description="Name / identifier of the inference model"
    )
    model_version: str = Field(
        default="0.0.0",
        description="Version string of the inference model"
    )
    provider: str = Field(
        default="none",
        description="Inference provider identifier (e.g., 'synthetic_demo', 'huggingface_local', 'none')"
    )
    is_synthetic: bool = Field(
        default=False,
        description="True if output is generated by a synthetic mock/demo provider; False for real trained models"
    )
    explanation: List[str] = Field(
        default_factory=list,
        description="Explainability notes, matched features, or token/SHAP rationale"
    )
    error: Optional[str] = Field(
        default=None,
        description="Error details if status is 'error' or 'unavailable'"
    )
